
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[s_PostQuarterlyInterset]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[s_PostQuarterlyInterset]
GO
CREATE PROCEDURE dbo.s_PostQuarterlyInterset	 
	 @SYSDATE as VARCHAR(15) = NULL
	,@USERID as VARCHAR(40) = NULL	
AS
BEGIN
	DECLARE @TIMEOFDAY VARCHAR(15)
	SELECT @TIMEOFDAY = convert(varchar, getdate(), 108)
	
		INSERT INTO SDTRAN (
			 ACCTNUM
			,TRANDATE
			,TRANSEQ
			,TRANCODE
			,TRANBBAL
			,TRANDEB
			,TRANCRE
			,TRANEBAL
			,CHKNUM
			,CHKBANK
			,CHKCODE
			,ADD_DATE
			,ADD_TIME
			,[USER]
			,[OVERRIDE]
			,PPOSTED
			,LPOSTED
			,TRANOLD
			,REVERSED
			)
		SELECT SM.ACCTNO
			,@SYSDATE
			,CASE 
				WHEN SM.LSEQ + 1 < 1000
					THEN SM.LSEQ + 1
				ELSE 1
				END
			,'INT'
			,SM.ACCTOBAL
			,0
			,INS.QTD
			,SM.ACCTOBAL + INS.QTD
			,'INTEREST'
			,''
			,''
			,@SYSDATE
			,@TIMEOFDAY
			,@USERID
			,''
			,0
			,0
			,0
			,0
		FROM SDMASTER SM
		RIGHT JOIN INTRST_S INS ON SM.ACCTNO = INS.ACCTNO
		WHERE SM.ACCTSTAT IN ('A','D')
		
		UPDATE SDMASTER
		SET SDMASTER.ACCTOBAL = SP.ACCTOBAL
			,SDMASTER.ACCTABAL = (SP.ACCTOBAL - SDMASTER.ACCTFLOATS)
			,SDMASTER.LSEQ = SP.LSEQ
		FROM (
			SELECT SM.ACCTNO
				,(SM.ACCTOBAL + (EX.MONTH1 + EX.MONTH2 + EX.MONTH3)) ACCTOBAL
				,(
					CASE 
						WHEN SM.LSEQ + 1 < 1000
							THEN SM.LSEQ + 1
						ELSE 1
						END
					) LSEQ
			FROM INTRST_S EX
			LEFT JOIN SDMASTER SM ON SM.ACCTNO = EX.ACCTNO
			) SP
		WHERE SDMASTER.ACCTNO = SP.ACCTNO
			AND SDMASTER.ACCTSTAT IN ('A','D')		
	END
GO

